config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  
  validates :name, :weight, :length, :height, :width, :sku, :supplier, presence: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :set_product_model, only: [:show, :edit, :update]

  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    get_suppliers_alphabetically()
  end

  def create
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save()
      flash[:notice] = 'Modelo de produto cadastrado com sucesso'
      redirect_to @product_model  # Quando a instancia do model (objeto) é passada em vez da rota/URL, o rails inerpreta e busca a rota :SHOW daquele objeto.
    else
      flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto'
      get_suppliers_alphabetically()
      render :new
    end

  end

  def show
    
  end
  
  private

  def set_product_model
    @product_model = ProductModel.find(params[:id])
  end

  def product_model_params
    params.require(:product_model).permit(:name, :weight, :length, :width, :height, :sku, :supplier_id)
  end

  def get_suppliers_alphabetically
    @suppliers_by_name = Supplier.all.order(:brand_name)
  end
end

app/views/product_models/_form.html.erb
<h1>Cadastrar Novo Modelo de Produto</h1>

<%= form_with(model: @product_model) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>
  <div>
    <%= f.label :length %>
    <%= f.number_field :length %>
  </div>
  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>
  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>
  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers_by_name, :id, :brand_name %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/product_models/index.html.erb
<h2>Modelos de Produtos</h2>
<%= link_to 'Cadastrar Novo Modelo de Produto', new_product_model_path %>

<% if @product_models.any? %>
  <div>
    <% @product_models.each do |pm| %>
      <h3><%= link_to pm.name, pm %></h3>
      <dl>
        <dt>SKU</dt>
        <dd><%= pm.sku %></dd>
        <dt>Fornecedor</dt>
        <dd><%= pm.supplier.brand_name %></dd>
      </dl>
    <% end %>
  </div>
<% else %>
  <p>Nenhum modelo de produto cadastrado.</p>
<% end %>


app/views/product_models/new.html.erb
<%= render partial: 'form' %>

<%= link_to 'Voltar', product_models_path %>

app/views/product_models/show.html.erb
<h2><%= @product_model.name %></h2>

<dl>
  <dt><strong>Fornecedor:</strong></dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
  <dt><strong>SKU:</strong></dt>
  <dd><%= @product_model.sku %></dd>
  <dt><strong>Dimensão:</strong></dt>
  <dd><%= @product_model.length %>cm x <%= @product_model.height %>cm x <%= @product_model.width %>cm</dd>
  <dt><strong>Peso:</strong></dt>
  <dd><%= @product_model.weight %> g</dd>
</dl>