config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models

  validates :corporate_name, :brand_name, :registration_number, :email, presence: true
  validates :registration_number, format: { with: /\A[0-9]{14}\z/ }
  validates :registration_number, uniqueness: true
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
  end

  def create
    supplier_params = params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :address, :city, :state, :email) #Strong Parameters
    @supplier = Supplier.new(supplier_params)

    if @supplier.save()
      flash[:notice] = 'Fornecedor cadastrado com sucesso.'
      redirect_to(suppliers_path)
    else
      flash.now[:notice] = 'Fornecedor não cadastrado.'
      render 'new'
    end
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end
  
  def update
    @supplier = Supplier.find(params[:id])
    supplier_params = params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :address, :city, :state, :email) #Strong Parameters

    if @supplier.update(supplier_params)
      flash[:notice] = 'Fornecedor atualizado com sucesso'
      redirect_to supplier_path(@supplier.id)
    else
      flash.now[:notice] = 'Não foi possível atualizar o fornecedor'
      render 'edit'
    end
  end

end

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
    <%= @supplier.errors.full_messages_for(:corporate_name)[0] if @supplier.errors.full_messages_for(:corporate_name).any? %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
    <%= @supplier.errors.full_messages_for(:brand_name)[0] if @supplier.errors.full_messages_for(:brand_name).any? %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
    <%= @supplier.errors.full_messages_for(:registration_number)[0] if @supplier.errors.full_messages_for(:registration_number).any? %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= @supplier.errors.full_messages_for(:email)[0] if @supplier.errors.full_messages_for(:email).any? %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h2>Editar Fornecedor</h2>

<%= render partial: 'form' %>

<%= link_to 'Cancelar', supplier_path(@supplier.id) %>

app/views/suppliers/index.html.erb
<h2>Fornecedores</h2>

<%= link_to('Cadastrar Fornecedor', new_supplier_path) %>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.brand_name, supplier_path(supplier.id) %></td>
          <td> <%= supplier.city %> - <%= supplier.state %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem fornecedores cadastrados.</p>
<% end %>
<br>
<%= link_to('Voltar', root_path) %>

app/views/suppliers/new.html.erb
<h2>Novo Fornecedor</h2>

<%= render partial: 'form' %>

<%= link_to 'Cancelar', suppliers_path %>

app/views/suppliers/show.html.erb
<h2>Fornecedor <%= @supplier.brand_name %></h2>
<h3><%= @supplier.corporate_name %></h3>

<dl>
  <dt>CNPJ:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt>Endereço:</dt>
  <dd><%= @supplier.address %> - <%= @supplier.city %> - <%= @supplier.state %></dd>
  <dt>CNPJ:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt>Email:</dt>
  <dd><%= @supplier.email %></dd>
</dl>

<%= link_to 'Editar', edit_supplier_path %>
<br><br>
<%= link_to 'Voltar', suppliers_path %>